name: "Send Telegram Message"
description: "Custom Action per enviar un missatge a Telegram"
author: "Erika Guillem"

inputs:
  name:
    description: "Nom de la persona que envia el missatge"
    required: true

runs:
  using: "node20"
  main: "index.js"
